# .semgrep.yml
rules:
  - id: no-eval
    languages: [javascript, typescript]
    message: "Avoid eval() – security risk."
    pattern: eval(...)
    severity: ERROR

  - id: no-unsafe-innerHTML
    languages: [typescript, javascript]
    message: "Avoid setting innerHTML directly."
    patterns:
      - pattern: $X.innerHTML = $Y
    severity: ERROR

  - id: no-broad-any
    languages: [typescript]
    message: "Broad 'any' type is not allowed."
    pattern: ": any"
    severity: ERROR

