import { Dog, Cat, Bird, Fish, Rabbit, PawPrint } from '@phosphor-icons/react';
import type { PetType } from '@/lib/pet-profile-templates';
import type { Step } from './create-pet-types';

export interface PetTypeOption {
  value: PetType;
  label: string;
  icon: typeof Dog;
  emoji: string;
}

export const PET_TYPES: PetTypeOption[] = [
  { value: 'dog', label: 'Dog', icon: Dog, emoji: '🐕' },
  { value: 'cat', label: 'Cat', icon: Cat, emoji: '🐈' },
  { value: 'bird', label: 'Bird', icon: Bird, emoji: '🦜' },
  { value: 'rabbit', label: 'Rabbit', icon: Rabbit, emoji: '🐰' },
  { value: 'fish', label: 'Fish', icon: Fish, emoji: '🐠' },
  { value: 'other', label: 'Other', icon: PawPrint, emoji: '🐾' },
];

export const PERSONALITY_TRAITS: Record<PetType, string[]> = {
  dog: [
    'Playful',
    'Calm',
    'Energetic',
    'Gentle',
    'Social',
    'Independent',
    'Affectionate',
    'Loyal',
    'Friendly',
    'Protective',
  ],
  cat: [
    'Independent',
    'Playful',
    'Calm',
    'Affectionate',
    'Curious',
    'Gentle',
    'Social',
    'Vocal',
    'Lap Cat',
    'Adventurous',
  ],
  bird: [
    'Vocal',
    'Social',
    'Playful',
    'Calm',
    'Affectionate',
    'Independent',
    'Curious',
    'Intelligent',
    'Active',
    'Gentle',
  ],
  rabbit: [
    'Gentle',
    'Playful',
    'Curious',
    'Social',
    'Calm',
    'Active',
    'Affectionate',
    'Independent',
    'Adventurous',
    'Friendly',
  ],
  fish: [
    'Peaceful',
    'Active',
    'Calm',
    'Social',
    'Curious',
    'Playful',
    'Gentle',
    'Independent',
    'Colorful',
    'Graceful',
  ],
  other: [
    'Playful',
    'Calm',
    'Curious',
    'Social',
    'Gentle',
    'Active',
    'Affectionate',
    'Independent',
    'Intelligent',
    'Friendly',
  ],
};

export const INTERESTS: Record<PetType, string[]> = {
  dog: [
    'Fetch',
    'Swimming',
    'Running',
    'Hiking',
    'Playing with Toys',
    'Training',
    'Socializing',
    'Chewing',
    'Exploring',
    'Cuddling',
  ],
  cat: [
    'Climbing',
    'Playing with Toys',
    'Window Watching',
    'Napping',
    'Hunting',
    'Exploring',
    'Scratching',
    'Cuddling',
    'Bird Watching',
    'Puzzle Games',
  ],
  bird: [
    'Singing',
    'Flying',
    'Playing with Toys',
    'Socializing',
    'Foraging',
    'Bathing',
    'Exploring',
    'Mimicking',
    'Climbing',
    'Training',
  ],
  rabbit: [
    'Hopping',
    'Digging',
    'Exploring',
    'Playing with Toys',
    'Foraging',
    'Socializing',
    'Grooming',
    'Napping',
    'Running',
    'Chewing',
  ],
  fish: [
    'Swimming',
    'Exploring',
    'Hiding',
    'Feeding Time',
    'Plants',
    'Decorations',
    'Schooling',
    'Bubble Nests',
    'Surface Activity',
    'Bottom Foraging',
  ],
  other: [
    'Exploring',
    'Treats',
    'Toys',
    'Cuddling',
    'Playing',
    'Exercise',
    'Social Time',
    'Training',
    'Napping',
    'Activities',
  ],
};

export const LOOKING_FOR: Record<PetType, string[]> = {
  dog: [
    'Playdate',
    'Walking Buddy',
    'Best Friend',
    'Training Partner',
    'Adventure Buddy',
    'Park Companion',
  ],
  cat: [
    'Playmate',
    'Cuddle Buddy',
    'Window Watching Friend',
    'Nap Companion',
    'Play Partner',
    'Friend',
  ],
  bird: [
    'Cage Mate',
    'Singing Partner',
    'Play Companion',
    'Social Buddy',
    'Friend',
    'Flock Member',
  ],
  rabbit: [
    'Bonded Pair',
    'Play Companion',
    'Cuddle Buddy',
    'Exercise Partner',
    'Friend',
    'Warren Mate',
  ],
  fish: [
    'Tank Mate',
    'School Member',
    'Peaceful Companion',
    'Breeding Partner',
    'Community Member',
    'Friend',
  ],
  other: ['Companion', 'Playmate', 'Friend', 'Social Buddy', 'Activity Partner', 'Best Friend'],
};

export const STEPS: Array<{ value: Step; label: string }> = [
  { value: 'type', label: 'Type' },
  { value: 'template', label: 'Template' },
  { value: 'basics', label: 'Basics' },
  { value: 'characteristics', label: 'Characteristics' },
  { value: 'personality', label: 'Personality' },
  { value: 'preferences', label: 'Preferences' },
  { value: 'photo', label: 'Photo' },
  { value: 'complete', label: 'Complete' },
];

