/**
 * Type declarations for lucide-react-native
 * The package includes its own types at dist/lucide-react-native.d.ts
 * This ensures TypeScript can resolve the module when types aren't automatically discovered
 */

declare module 'lucide-react-native' {
  import type { ComponentProps } from 'react';
  import type { SvgProps } from 'react-native-svg';

  export interface IconProps extends SvgProps {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
  }

  export type LucideIcon = React.ComponentType<IconProps>;

  // Export icons used in the codebase
  export const Check: LucideIcon;
  export const Mic: LucideIcon;
  export const MicOff: LucideIcon;
  export const Video: LucideIcon;
  export const VideoOff: LucideIcon;
  export const PhoneOff: LucideIcon;
  
  // Add other common icons that might be used
  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const XCircle: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Plus: LucideIcon;
  export const Minus: LucideIcon;
  export const X: LucideIcon;
  export const Search: LucideIcon;
  export const Settings: LucideIcon;
  export const User: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const Calendar: LucideIcon;
  export const Clock: LucideIcon;
  export const Heart: LucideIcon;
  export const Star: LucideIcon;
  export const Home: LucideIcon;
  export const Menu: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const Edit: LucideIcon;
  export const Trash: LucideIcon;
  export const Download: LucideIcon;
  export const Upload: LucideIcon;
  export const Image: LucideIcon;
  export const Camera: LucideIcon;
  export const File: LucideIcon;
  export const Folder: LucideIcon;
  export const Lock: LucideIcon;
  export const Unlock: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Bell: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Send: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Link: LucideIcon;
  export const Share: LucideIcon;
  export const Copy: LucideIcon;
  export const Info: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const CreditCard: LucideIcon;
  export const DollarSign: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const Package: LucideIcon;
  export const Truck: LucideIcon;
  export const MapPin: LucideIcon;
  export const Navigation: LucideIcon;
  export const Compass: LucideIcon;
  export const Globe: LucideIcon;
  export const Wifi: LucideIcon;
  export const WifiOff: LucideIcon;
  export const Battery: LucideIcon;
  export const BatteryCharging: LucideIcon;
  export const Zap: LucideIcon;
  export const Sun: LucideIcon;
  export const Moon: LucideIcon;
  export const Cloud: LucideIcon;
  export const CloudRain: LucideIcon;
  export const CloudSnow: LucideIcon;
  export const Wind: LucideIcon;
  export const Droplet: LucideIcon;
  export const Thermometer: LucideIcon;
  export const Filter: LucideIcon;
  export const Sliders: LucideIcon;
  export const Grid: LucideIcon;
  export const List: LucideIcon;
  export const Layout: LucideIcon;
  export const Columns: LucideIcon;
  export const Rows: LucideIcon;
  export const Maximize: LucideIcon;
  export const Minimize: LucideIcon;
  export const Maximize2: LucideIcon;
  export const Minimize2: LucideIcon;
  export const RotateCw: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const RefreshCcw: LucideIcon;
  export const Repeat: LucideIcon;
  export const Shuffle: LucideIcon;
  export const SkipBack: LucideIcon;
  export const SkipForward: LucideIcon;
  export const Play: LucideIcon;
  export const Pause: LucideIcon;
  export const Stop: LucideIcon;
  export const Volume: LucideIcon;
  export const Volume1: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const Headphones: LucideIcon;
  export const Radio: LucideIcon;
  export const Music: LucideIcon;
  export const Music2: LucideIcon;
  export const Disc: LucideIcon;
  export const Film: LucideIcon;
  export const Tv: LucideIcon;
  export const Monitor: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Tablet: LucideIcon;
  export const Laptop: LucideIcon;
  export const Printer: LucideIcon;
  export const Keyboard: LucideIcon;
  export const Mouse: LucideIcon;
  export const HardDrive: LucideIcon;
  export const Server: LucideIcon;
  export const Database: LucideIcon;
  export const Cpu: LucideIcon;
  export const MemoryStick: LucideIcon;
  export const Usb: LucideIcon;
  export const Bluetooth: LucideIcon;
  export const BluetoothConnected: LucideIcon;
  export const BluetoothOff: LucideIcon;
  export const Signal: LucideIcon;
  export const Wifi2: LucideIcon;
  export const WifiOff2: LucideIcon;
  export const Circle: LucideIcon;
  export const Square: LucideIcon;
  export const Triangle: LucideIcon;
  export const Hexagon: LucideIcon;
  export const Octagon: LucideIcon;
  export const Pentagon: LucideIcon;
  export const Diamond: LucideIcon;
  export const Star2: LucideIcon;
  export const Heart2: LucideIcon;
  export const HeartHandshake: LucideIcon;
  export const HeartPulse: LucideIcon;
  export const HeartCrack: LucideIcon;
  export const HeartOff: LucideIcon;
  export const HeartFill: LucideIcon;
  export const HeartHalf: LucideIcon;
  export const HeartHalfFill: LucideIcon;
  export const HeartHalfOff: LucideIcon;
  export const HeartHalfCrack: LucideIcon;
  export const HeartHalfPulse: LucideIcon;
  export const HeartHalfHandshake: LucideIcon;
}
