/**
 * Extended theme system with 18 themes
 * Location: src/theme/themes-extended.ts
 */

import type { Theme } from './themes'

// Additional themes beyond the base 5
export const additionalThemes: Record<string, Omit<Theme, 'id'>> = {
  'forest-nature': {
    name: 'Forest Nature',
    colors: {
      background: '#F5F5E6',
      foreground: '#E8E8D3',
      primary: '#4A7C59',
      secondary: '#3D5A4A',
      accent: '#7FB069',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#5C5C4A',
      border: '#C8C8B8',
      success: '#4CAF50',
      danger: '#D32F2F',
      warning: '#F57C00',
      info: '#1976D2',
    },
  },
  'purple-dream': {
    name: 'Purple Dream',
    colors: {
      background: '#F3E5F5',
      foreground: '#E1BEE7',
      primary: '#9C27B0',
      secondary: '#7B1FA2',
      accent: '#BA68C8',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#6A1B9A',
      border: '#CE93D8',
      success: '#4CAF50',
      danger: '#E91E63',
      warning: '#FF9800',
      info: '#9C27B0',
    },
  },
  'midnight-blue': {
    name: 'Midnight Blue',
    colors: {
      background: '#1A1A2E',
      foreground: '#16213E',
      primary: '#0F3460',
      secondary: '#533483',
      accent: '#E94560',
      card: '#2A2A3E',
      textPrimary: '#FFFFFF',
      textSecondary: '#B0B0C0',
      border: '#3A3A4E',
      success: '#66BB6A',
      danger: '#EF5350',
      warning: '#FFB74D',
      info: '#42A5F5',
    },
  },
  'golden-hour': {
    name: 'Golden Hour',
    colors: {
      background: '#FFF8E1',
      foreground: '#FFECB3',
      primary: '#FFC107',
      secondary: '#FFA000',
      accent: '#FFD54F',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#8B6F00',
      border: '#FFE082',
      success: '#4CAF50',
      danger: '#E63946',
      warning: '#FFA726',
      info: '#2196F3',
    },
  },
  'cherry-blossom': {
    name: 'Cherry Blossom',
    colors: {
      background: '#FFF0F5',
      foreground: '#FFE4E9',
      primary: '#E91E63',
      secondary: '#C2185B',
      accent: '#F48FB1',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#AD1457',
      border: '#F8BBD0',
      success: '#4CAF50',
      danger: '#E91E63',
      warning: '#FF9800',
      info: '#2196F3',
    },
  },
  'emerald-garden': {
    name: 'Emerald Garden',
    colors: {
      background: '#E8F5E9',
      foreground: '#C8E6C9',
      primary: '#4CAF50',
      secondary: '#388E3C',
      accent: '#66BB6A',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#2E7D32',
      border: '#A5D6A7',
      success: '#4CAF50',
      danger: '#E91E63',
      warning: '#FF9800',
      info: '#2196F3',
    },
  },
  'stormy-gray': {
    name: 'Stormy Gray',
    colors: {
      background: '#FAFAFA',
      foreground: '#F5F5F5',
      primary: '#616161',
      secondary: '#424242',
      accent: '#757575',
      card: '#FFFFFF',
      textPrimary: '#212121',
      textSecondary: '#757575',
      border: '#E0E0E0',
      success: '#4CAF50',
      danger: '#D32F2F',
      warning: '#F57C00',
      info: '#1976D2',
    },
  },
  'royal-purple': {
    name: 'Royal Purple',
    colors: {
      background: '#EDE7F6',
      foreground: '#D1C4E9',
      primary: '#673AB7',
      secondary: '#512DA8',
      accent: '#9575CD',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#512DA8',
      border: '#B39DDB',
      success: '#4CAF50',
      danger: '#E91E63',
      warning: '#FF9800',
      info: '#673AB7',
    },
  },
  'arctic-ice': {
    name: 'Arctic Ice',
    colors: {
      background: '#E0F2F1',
      foreground: '#B2DFDB',
      primary: '#00897B',
      secondary: '#00695C',
      accent: '#26A69A',
      card: '#FFFFFF',
      textPrimary: '#004D40',
      textSecondary: '#00695C',
      border: '#80CBC4',
      success: '#4CAF50',
      danger: '#E91E63',
      warning: '#FF9800',
      info: '#00897B',
    },
  },
  'crimson-red': {
    name: 'Crimson Red',
    colors: {
      background: '#FFEBEE',
      foreground: '#FFCDD2',
      primary: '#D32F2F',
      secondary: '#C62828',
      accent: '#E57373',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#B71C1C',
      border: '#EF9A9A',
      success: '#4CAF50',
      danger: '#D32F2F',
      warning: '#FF9800',
      info: '#1976D2',
    },
  },
  'amber-glow': {
    name: 'Amber Glow',
    colors: {
      background: '#FFF8E1',
      foreground: '#FFECB3',
      primary: '#FF6F00',
      secondary: '#E65100',
      accent: '#FF9800',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#BF360C',
      border: '#FFE082',
      success: '#4CAF50',
      danger: '#E63946',
      warning: '#FF6F00',
      info: '#2196F3',
    },
  },
  'deep-space': {
    name: 'Deep Space',
    colors: {
      background: '#0D1117',
      foreground: '#161B22',
      primary: '#58A6FF',
      secondary: '#388BFD',
      accent: '#79C0FF',
      card: '#161B22',
      textPrimary: '#F0F6FC',
      textSecondary: '#8B949E',
      border: '#30363D',
      success: '#3FB950',
      danger: '#F85149',
      warning: '#D29922',
      info: '#58A6FF',
    },
  },
  'sakura-pink': {
    name: 'Sakura Pink',
    colors: {
      background: '#FCE4EC',
      foreground: '#F8BBD0',
      primary: '#EC407A',
      secondary: '#E91E63',
      accent: '#F48FB1',
      card: '#FFFFFF',
      textPrimary: '#1A1A1A',
      textSecondary: '#C2185B',
      border: '#F8BBD0',
      success: '#4CAF50',
      danger: '#EC407A',
      warning: '#FF9800',
      info: '#E91E63',
    },
  },
}

