import type { CommunityPost } from './community-types';
import { generateULID } from './utils';
import { logger } from './logger';

export function generateCommunitySeedData(): CommunityPost[] {
  const samplePosts: CommunityPost[] = [
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-001',
      authorName: 'Sarah Johnson',
      authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      kind: 'photo',
      petIds: ['pet-001'],
      text: '🐾 Luna had her first training session today and she was amazing! So proud of my little girl. She learned "sit" and "stay" in just one hour. Any tips for teaching "come" next?',
      media: [
        {
          id: 'img-001',
          type: 'photo',
          url: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800',
          thumbnail: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=320',
        },
      ],
      tags: ['training', 'puppy', 'goldenretriever'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 24,
        comments: 5,
        saves: 8,
        shares: 2,
        impressions: 156,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 156,
      reactionsCount: 24,
      commentsCount: 5,
      sharesCount: 2,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-002',
      authorName: 'Mike Chen',
      authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      kind: 'photo',
      petIds: ['pet-002'],
      text: 'Beach day with Max! 🏖️ He discovered that waves are both exciting and scary at the same time 😂 Swipe to see his reaction!',
      media: [
        {
          id: 'img-002',
          type: 'photo',
          url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800',
          thumbnail: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=320',
        },
        {
          id: 'img-003',
          type: 'photo',
          url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
          thumbnail: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=320',
        },
      ],
      tags: ['beach', 'funday', 'labradorretriever'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 42,
        comments: 8,
        saves: 12,
        shares: 5,
        impressions: 234,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 234,
      reactionsCount: 42,
      commentsCount: 8,
      sharesCount: 5,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-003',
      authorName: 'Emma Rodriguez',
      authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      kind: 'photo',
      petIds: ['pet-003'],
      text: 'Can we talk about how adorable Milo looks in his new sweater? 🧶 Winter is coming and he is READY! #fashionpet #cozyvibes',
      media: [
        {
          id: 'img-004',
          type: 'photo',
          url: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800',
          thumbnail: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=320',
        },
      ],
      tags: ['fashion', 'winter', 'pomeranian'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 67,
        comments: 15,
        saves: 23,
        shares: 11,
        impressions: 389,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 389,
      reactionsCount: 67,
      commentsCount: 15,
      sharesCount: 11,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-004',
      authorName: 'James Wilson',
      authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      kind: 'photo',
      petIds: ['pet-004'],
      text: "Bella made a new friend at the dog park today! 🐕 They played non-stop for an hour. It's so important for puppies to socialize early. Does anyone know of good puppy playgroups in the area?",
      media: [
        {
          id: 'img-005',
          type: 'photo',
          url: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
          thumbnail: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=320',
        },
      ],
      tags: ['socialization', 'dogpark', 'puppyplaydate'],
      visibility: 'public',
      location: {
        lat: 37.7749,
        lon: -122.4194,
        lng: -122.4194,
        placeId: 'park-001',
        placeName: 'Golden Gate Park',
      },
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 31,
        comments: 12,
        saves: 6,
        shares: 3,
        impressions: 178,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 178,
      reactionsCount: 31,
      commentsCount: 12,
      sharesCount: 3,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-005',
      authorName: 'Sofia Martinez',
      authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      kind: 'photo',
      petIds: ['pet-005'],
      text: '❤️ Celebrating 2 years with my rescue kitty, Oliver! From scared shelter cat to confident couch king. Adoption stories are the best stories. #adoptdontshop',
      media: [
        {
          id: 'img-006',
          type: 'photo',
          url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800',
          thumbnail: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=320',
        },
        {
          id: 'img-007',
          type: 'photo',
          url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800',
          thumbnail: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=320',
        },
      ],
      tags: ['adoptdontshop', 'rescuecat', 'anniversary'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 89,
        comments: 22,
        saves: 34,
        shares: 18,
        impressions: 512,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 512,
      reactionsCount: 89,
      commentsCount: 22,
      sharesCount: 18,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-006',
      authorName: 'Alex Thompson',
      authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      kind: 'video',
      petIds: ['pet-006'],
      text: "🎾 Watch Charlie catch his first frisbee! Took us 3 weeks of practice but he finally got it! The slow-mo replay is *chef's kiss* 😂 #frisbeedog #prouddogdad",
      media: [
        {
          id: 'vid-001',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
          thumbnail: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800',
          duration: 15,
          width: 1280,
          height: 720,
        },
      ],
      tags: ['frisbee', 'training', 'bordercollie', 'slowmo'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 156,
        comments: 34,
        saves: 67,
        shares: 42,
        impressions: 892,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 892,
      reactionsCount: 156,
      commentsCount: 34,
      sharesCount: 42,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-007',
      authorName: 'Rachel Kim',
      authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      kind: 'video',
      petIds: ['pet-007'],
      text: "POV: You just told your husky it's time for a walk 🤣 The dramatic entrance, the spinning, the HOWLS! Koda is living his best life. Turn on sound! 🔊",
      media: [
        {
          id: 'vid-002',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
          thumbnail: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800',
          duration: 22,
          width: 1920,
          height: 1080,
        },
      ],
      tags: ['husky', 'funny', 'drama', 'walktime'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 234,
        comments: 56,
        saves: 89,
        shares: 78,
        impressions: 1453,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 1453,
      reactionsCount: 234,
      commentsCount: 56,
      sharesCount: 78,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-008',
      authorName: 'David Brown',
      authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      kind: 'video',
      petIds: ['pet-008'],
      text: '🌊 First time at the lake and Daisy is a NATURAL swimmer! She went from scared on the shore to full-on doggy paddle in 5 minutes. So proud! 💙',
      media: [
        {
          id: 'vid-003',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
          thumbnail: 'https://images.unsplash.com/photo-1544568104-5b7eb8189dd4?w=800',
          duration: 18,
          width: 1280,
          height: 720,
        },
      ],
      tags: ['swimming', 'lake', 'goldenretriever', 'firsttime'],
      visibility: 'public',
      location: {
        lat: 34.0522,
        lon: -118.2437,
        lng: -118.2437,
        placeId: 'lake-001',
        placeName: 'Lake Tahoe',
      },
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 178,
        comments: 41,
        saves: 52,
        shares: 29,
        impressions: 967,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 967,
      reactionsCount: 178,
      commentsCount: 41,
      sharesCount: 29,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-009',
      authorName: 'Jennifer Lee',
      authorAvatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150',
      kind: 'video',
      petIds: ['pet-009'],
      text: 'Zoomies at 3 AM be like... 😴💨 Caught Luna on the security cam doing her nightly laps around the house. Why are cats so weird? I love her 😂',
      media: [
        {
          id: 'vid-004',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
          thumbnail: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800',
          duration: 12,
          width: 1920,
          height: 1080,
        },
      ],
      tags: ['zoomies', 'catsofinstagram', 'nightowl', 'funny'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 312,
        comments: 67,
        saves: 124,
        shares: 93,
        impressions: 2341,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 2341,
      reactionsCount: 312,
      commentsCount: 67,
      sharesCount: 93,
      featured: false,
    },
    {
      id: generateULID(),
      _id: generateULID(),
      authorId: 'user-010',
      authorName: 'Chris Anderson',
      authorAvatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=150',
      kind: 'video',
      petIds: ['pet-010'],
      text: '🎉 Teaching Rocky some new tricks! He just learned how to "play dead" and I\'m DECEASED 💀 Watch till the end for the cutest thing ever! #smartdog #tricks',
      media: [
        {
          id: 'vid-005',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
          thumbnail: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=800',
          duration: 25,
          width: 1280,
          height: 720,
        },
      ],
      tags: ['tricks', 'training', 'germanshepherd', 'playdead'],
      visibility: 'public',
      createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
      metrics: {
        likes: 267,
        comments: 48,
        saves: 103,
        shares: 61,
        impressions: 1678,
      },
      status: 'active',
      moderation: {
        state: 'approved',
        reasons: [],
      },
      viewsCount: 1678,
      reactionsCount: 267,
      commentsCount: 48,
      sharesCount: 61,
      featured: false,
    },
  ];

  return samplePosts;
}

export async function initializeCommunityData(): Promise<void> {
  const existingPosts = await (
    window as Window & { spark?: { kv?: { get: <T>(key: string) => Promise<T | null> } } }
  ).spark?.kv?.get<CommunityPost[]>('community:posts');

  if (!existingPosts || existingPosts.length === 0) {
    const seedPosts = generateCommunitySeedData();
    await (
      window as Window & { spark?: { kv?: { set: <T>(key: string, value: T) => Promise<void> } } }
    ).spark?.kv?.set('community:posts', seedPosts);
    logger.info('Community seed data initialized', { postsCount: seedPosts.length });
  }
}
